import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });



export const metadata = {
  title: {
    
    default: "Ak Tech World - IT solutions - Managed IT services",
    template: "%s | Ak Tech World ",
  },
  description: "Generated by Ak Tech World"
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
      <Navbar></Navbar>

      
      
      {children}
      
      
      <footer style={{backgroundColor:'lightskyblue'}}>
      <p>Footer</p>
      </footer>

      </body>
    </html>
  );
}
